version: 2.1

commands:
  install_dependencies:
    steps:
      - run:
          git submodule update --init --recursive
      - restore_cache:
          name: Restore NPM cache
          keys:
            - npm-packages-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          name: Save NPM cache
          key: npm-packages-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

jobs:
  test:
    docker:
      - image: circleci/node:11.15
      - image: circleci/python:3.6.4
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - install_dependencies
      - run: 
        command: |
          pip install vyper==0.1.0
          npm test

workflows:
  version: 2
  test:
    jobs:
      - test
